version: "3"
services:
  react-app-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:4200" #80 -while using aws | 3000 -react
    volumes:
      - /app/node_modules
      - .:/src
